	pipeline {
    agent any
	tools {
	    maven 'MAVEN 3.8.4'
	}
    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'MAVEN 3.8.4') {
                	
                    sh 'mvn clean compile'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : 'MAVEN 3.8.4') {
                    sh 'mvn test'
                }
            }
        }


        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'MAVEN 3.8.4') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}