	pipeline {
    agent any
	tools {
	    maven 'MAVEN 3.8.4'
	}
    stages {
        stage ('Compile Stage') {

            steps {           
                    bat 'mvn -f /mvnPipelineDemo/pom.xml clean compile'                
            }
        }

        stage ('Testing Stage') {

            steps {               
                    bat 'mvn test'                
            }
        }

        stage ('Deployment Stage') {
            steps {               
                    bat 'mvn deploy'               
            }
        }
    }
}